version: '3'
services:
  spring-boot-app:
    build:
      context: spring-boot-service
    ports:
      - "8080:8080"

  vue-app:
    build:
      context: vue-frontend
    volumes:
      - './vue-frontend:/app'
      - '/app/node_modules'
    ports:
      - "8081:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
